# Generated by Django 3.0.6 on 2020-06-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='cover_image_src',
            field=models.FileField(upload_to=''),
        ),
    ]
