# Generated by Django 3.0.6 on 2020-06-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_diary', '0003_auto_20200604_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AddConstraint(
            model_name='diary',
            constraint=models.UniqueConstraint(fields=('slug', 'user'), name='unique_slug'),
        ),
    ]
