# Generated by Django 3.0.6 on 2020-06-04 05:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_diary', '0004_auto_20200604_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='cover_image_src',
        ),
        migrations.AddField(
            model_name='diary',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
